# Generated by Django 3.2 on 2022-05-24 16:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0004_alter_book_rack'),
        ('author', '0002_racknum'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RackNum',
        ),
    ]
