# Generated by Django 3.2 on 2022-05-18 13:50

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('place', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Campus',
            new_name='Sede',
        ),
        migrations.RenameField(
            model_name='rack',
            old_name='campus',
            new_name='sede',
        ),
        migrations.AlterField(
            model_name='rack',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('93530d86-6906-4bc8-8d78-1bab20b058d1')),
        ),
    ]
