# Generated by Django 3.2 on 2022-05-24 14:24

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('place', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rack',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('030488f3-9260-4c77-b1ca-a7e743697c79')),
        ),
    ]
