# Generated by Django 3.2 on 2022-05-24 16:14

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('place', '0002_alter_rack_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rack',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('613f5436-58aa-4d9f-85df-bc22b3ed45c7')),
        ),
    ]
