# Generated by Django 3.2 on 2022-05-18 14:01

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('place', '0002_auto_20220518_0850'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rack',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('965d94be-6fd4-4541-871e-8d57da91d0c6')),
        ),
    ]
