# Generated by Django 3.2 on 2022-05-24 16:16

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('place', '0003_alter_rack_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rack',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('7a67b1f4-712c-4484-9948-984118798e8e')),
        ),
    ]
