# Generated by Django 3.2 on 2022-05-18 22:28

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('place', '0003_alter_rack_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rack',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('c15712c5-8bf4-40e6-9fbf-a67fa53a424b')),
        ),
    ]
