# Generated by Django 3.2 on 2022-05-18 22:31

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('place', '0004_alter_rack_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rack',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('a619e335-84cb-48f8-b373-783b90cf8150')),
        ),
    ]
