# Generated by Django 3.2 on 2022-05-18 22:38

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('place', '0006_alter_rack_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rack',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('402db634-6fd0-475c-b84a-ed3480a875d4')),
        ),
    ]
