# Generated by Django 3.2 on 2022-05-19 02:52

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('place', '0007_alter_rack_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rack',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('6765e294-5427-4f3a-a5fa-24cebf6401ff')),
        ),
    ]
