# Generated by Django 3.2 on 2022-05-19 14:24

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('place', '0008_alter_rack_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rack',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('c0ed3ab0-f862-4482-9544-66b54f99be7b')),
        ),
    ]
