# Generated by Django 3.2 on 2022-05-19 16:30

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('place', '0009_alter_rack_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rack',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('13c0428a-0c70-4cfd-a512-cde5b6091e39')),
        ),
    ]
