# Generated by Django 3.2 on 2022-05-19 16:51

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('place', '0010_alter_rack_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rack',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('aea5d671-cc2d-49d9-b3c0-2bcba0abb585')),
        ),
    ]
