# Generated by Django 3.2 on 2022-05-19 19:41

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('place', '0012_alter_rack_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rack',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('748d9ebc-e270-4f44-8f32-a239836adcd2')),
        ),
    ]
