# Generated by Django 3.2 on 2022-05-24 16:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('author', '0002_racknum'),
        ('book', '0002_book_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='rack',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='author.racknum'),
            preserve_default=False,
        ),
    ]
