# Generated by Django 3.2 on 2022-05-24 16:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rack', '0001_initial'),
        ('book', '0003_book_rack'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='rack',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rack.racknum'),
        ),
    ]
